<?php
/**
 * Standalone Contact Form Handler & Inquiries Mailer
 * Auto-generated by Dynamicleo CMS for S1.
 * Compatible with PHP 7.4+, 8.0, 8.1, 8.2, 8.3 on cPanel, Apache, Nginx, LiteSpeed.
 */

// Allow cross-origin requests
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method Not Allowed. Please submit via POST.']);
    exit;
}

// 1. Recipient Configuration
$to_email = "as@mail.com";
$site_name = "fulg";

// 2. Parse Incoming Payload (Supports JSON fetch and standard form-data)
$contentType = isset($_SERVER['CONTENT_TYPE']) ? trim($_SERVER['CONTENT_TYPE']) : '';
$data = [];

if (stripos($contentType, 'application/json') !== false) {
    $rawInput = file_get_contents('php://input');
    $decoded = json_decode($rawInput, true);
    if (is_array($decoded)) {
        $data = $decoded;
    }
}

if (empty($data)) {
    $data = $_POST;
}

// 3. Honeypot Anti-Spam Check
if (!empty($data['_gotcha']) || !empty($data['website_url_hp'])) {
    echo json_encode(['success' => true, 'message' => 'Thank you for your submission.']);
    exit;
}

// 4. Sanitize and Extract Fields
function clean_val($val) {
    if (is_array($val)) return implode(', ', array_map('clean_val', $val));
    return htmlspecialchars(strip_tags(trim((string)$val)), ENT_QUOTES, 'UTF-8');
}

$name = isset($data['name']) ? clean_val($data['name']) : '';
$email = isset($data['email']) ? filter_var(trim($data['email']), FILTER_VALIDATE_EMAIL) : false;
$phone = isset($data['phone']) ? clean_val($data['phone']) : '';
$company = isset($data['company']) ? clean_val($data['company']) : '';
$subject_raw = isset($data['product']) ? clean_val($data['product']) : (isset($data['subject']) ? clean_val($data['subject']) : 'New Commercial Inquiry');
$notes = isset($data['notes']) ? clean_val($data['notes']) : (isset($data['message']) ? clean_val($data['message']) : (isset($data['details']) ? clean_val($data['details']) : ''));
$quantity = isset($data['quantity']) ? clean_val($data['quantity']) : '';
$incoterm = isset($data['incoterm']) ? clean_val($data['incoterm']) : '';
$destination = isset($data['destination']) ? clean_val($data['destination']) : '';

// Validation
if (empty($name) || !$email) {
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'error' => 'Please provide a valid name and email address.'
    ]);
    exit;
}

// Prevent Email Header Injection
$subject = str_replace(["\r", "\n"], ' ', "New Inquiry: " . ($company ? $company . " - " : "") . $subject_raw);
$name_clean = str_replace(["\r", "\n"], ' ', $name);

// 5. Construct HTML & Plaintext Email
$date_str = date('Y-m-d H:i:s T');
$ip = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : 'Unknown';

$body_html = "
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #f8fafc; color: #1e293b; padding: 24px; }
    .card { max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
    .header { background: #0f172a; color: #ffffff; padding: 24px; text-align: left; }
    .header h2 { margin: 0 0 6px 0; font-size: 20px; font-weight: 700; color: #ffffff; }
    .header p { margin: 0; font-size: 13px; color: #94a3b8; }
    .content { padding: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { padding: 12px 8px; text-align: left; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
    th { color: #64748b; font-weight: 600; width: 35%; }
    td { color: #0f172a; font-weight: 500; }
    .footer { background: #f8fafc; padding: 16px 24px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class='card'>
    <div class='header'>
      <h2>New Lead / Commercial Inquiry</h2>
      <p>" . htmlspecialchars($site_name) . " Website Submission</p>
    </div>
    <div class='content'>
      <table>
        <tr><th>Full Name</th><td>" . htmlspecialchars($name) . "</td></tr>
        <tr><th>Email Address</th><td><a href='mailto:" . htmlspecialchars($email) . "'>" . htmlspecialchars($email) . "</a></td></tr>
        " . ($company ? "<tr><th>Company / Org</th><td>" . htmlspecialchars($company) . "</td></tr>" : "") . "
        " . ($phone ? "<tr><th>Phone / WhatsApp</th><td>" . htmlspecialchars($phone) . "</td></tr>" : "") . "
        " . ($subject_raw ? "<tr><th>Product / Topic</th><td>" . htmlspecialchars($subject_raw) . "</td></tr>" : "") . "
        " . ($quantity ? "<tr><th>Quantity</th><td>" . htmlspecialchars($quantity) . "</td></tr>" : "") . "
        " . ($incoterm ? "<tr><th>Incoterms</th><td>" . htmlspecialchars($incoterm) . "</td></tr>" : "") . "
        " . ($destination ? "<tr><th>Destination Port</th><td>" . htmlspecialchars($destination) . "</td></tr>" : "") . "
        " . ($notes ? "<tr><th>Notes / Details</th><td>" . nl2br(htmlspecialchars($notes)) . "</td></tr>" : "") . "
        <tr><th>Submitted At</th><td>" . htmlspecialchars($date_str) . "</td></tr>
        <tr><th>Visitor IP</th><td>" . htmlspecialchars($ip) . "</td></tr>
      </table>
    </div>
    <div class='footer'>
      Dispatched automatically from your website form backend via contact.php.
    </div>
  </div>
</body>
</html>
";

$serverHost = isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : 'clientsite.com';
$headers = [];
$headers[] = "MIME-Version: 1.0";
$headers[] = "Content-Type: text/html; charset=UTF-8";
$headers[] = "From: " . $site_name . " <noreply@" . $serverHost . ">";
$headers[] = "Reply-To: " . $name_clean . " <" . $email . ">";
$headers[] = "X-Mailer: PHP/" . phpversion();

$mailSent = @mail($to_email, $subject, $body_html, implode("\r\n", $headers));

echo json_encode([
    'success' => true,
    'message' => 'Your inquiry has been received. Our team will contact you shortly.',
    'mailSent' => (bool)$mailSent
]);
